### ISSUE TITLE
Getting the binding_sites.csv matrix 

### ISSUE THREAD

**Issue by cakeinspace** [sarajimenez/fatecompass#1]
Hey how do I get the binding_sites.csv matrix for the human and mouse. I understand its from the downloads section of the swissregulon website, but what are the preprocessing steps involved. Thanks a lot!!

**Comment by sarajimenez** [comment]
Hi, 

Thank you for your interest! We provided the binding site matrix for human and mouse in the folder [binding_site_matrices](binding_site_matrices/). 

The pre-processing steps are detailed in the methods section of our [pre-print](https://doi.org/10.1101/2022.04.01.486696). In a nutshell, we downloaded the binding site predictions from Swissregulon; then we summarized the TF binding sites in a matrix of site counts by summing the posterior probabilities for each motif in the promoter of each gene. We defined a promoter as the TSS +/- 1kb. 

HTH :)
